// module-federation-vite-react/host/src/components/Counter.tsx
import { useState } from 'react';

export default () => {
  const [count, setCount] = useState<number>(0);

  return (
    <button
      style={{
        border: '0 solid #e2e8f0',
        marginTop: '10px',
        backgroundColor: 'rgb(246, 179, 82)',
        borderRadius: '.25rem',
        fontWeight: '700',
        padding: '.5rem 1rem .5rem 1rem',
        color: 'rgb(24, 24, 24)',
      }}
      onClick={() => setCount(count + 1)}
    >
      Host counter: {count}
    </button>
  );
};

// module-federation-vite-angular/host/src/counter.component.ts
import { Component, signal } from '@angular/core';

@Component({
	selector: 'app-counter',
	standalone: true,
	template: `
		<button
			style="
        border: 0 solid #e2e8f0;
        margin-top: 10px;
        backgroundColor: rgb(246, 179, 82);
				borderRadius: .25rem;
				fontWeight: 700;
				padding: .5rem 1rem .5rem 1rem;
				color: rgb(24, 24, 24);
			"
			(click)="increment()"
		>
			Host counter: {{ count() }}
		</button>
	`,
})
export class CounterComponent {
	count = signal(0);

	increment() {
		this.count.update((value) => ++value);
	}
}
