// module-federation-vite-solid/host/src/components/Counter.tsx
import { createSignal } from "solid-js";

export default () => {
	const [count, setCount] = createSignal(0);
	return (
		<button
			style={{
				border: '0 solid #e2e8f0',
				"margin-top": '10px',
				"background-color": 'rgb(246, 179, 82)',
				"border-radius": '.25rem',
				"font-weight": '700',
				padding: '.5rem 1rem .5rem 1rem',
				color: 'rgb(24, 24, 24)',
			}}
			onClick={() => setCount(count() + 1)}
		>
			Host counter: {count()}
		</button>
	);
};

// vite-react-microfrontends/host/src/components/Counter.tsx
import React from 'react';

export default () => {
  const [count, setCount] = React.useState<number>(0);

  return (
    <button
      style={{
        border: '0 solid #e2e8f0',
        marginTop: '10px',
        backgroundColor: 'rgb(246, 179, 82)',
        borderRadius: '.25rem',
        fontWeight: '700',
        padding: '.5rem 1rem .5rem 1rem',
        color: 'rgb(24, 24, 24)',
      }}
      onClick={() => setCount(count + 1)}
    >
      Host counter: {count}
    </button>
  );
};
